stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Test
    displayName: Testing
    steps:
    - script: type $(Build.SourcesDirectory)/DockerfileDB/Dockerfile
      displayName: print dockerfile  

  - job: Build
    displayName: Build
    dependsOn: Test
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/DockerfileDB/Dockerfile'
        tags: |
          $(tag)
